/***************************************************************
    *  DO NOT EDIT THIS FILE!
    *         
    *  This file is automatically generated by HP Service Test.
    *  Manually changing the contents of this file may result in 
    *  loss of information.
    *          
    *  To edit the test, open the file ‘Booking Process.st’ 
    *  in HP Service Test.
     ***************************************************************/
    
    namespace Script
    {
    using System;
    using System.Text;
    using System.Threading;
    using System.Xml;
    using System.Xml.Schema;
    using HP.ST.Fwk.ReporterFWK;
    using HP.ST.Shared.Utilities;
    using HP.ST.Ext.BindingImpl.Getters;
    using HP.ST.Ext.BindingImpl.Setters;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.PropInfo;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.Getters;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.Setters;
    using HP.ST.Fwk.RunTimeFWK;
    using HP.ST.Fwk.RunTimeFWK.Utilities;
    using HP.ST.Fwk.RunTimeFWK.HelperClasses;
    using HP.ST.Fwk.RunTimeFWK.CompositeActivities;
    using HP.ST.Ext.BindingImpl.Setters.DataSourceSetters;
    using HP.ST.Fwk.JVMLoader;
    using System.IO;
    using System.Collections.Generic;
    using System.Reflection;
    using HP.ST.Fwk.SOAReplayAPI;
    using HP.ST.Fwk.UFTLicensing;
    
    
    
    public partial class WorkFlowScript : STWorkFlowScriptBase
    {    
    	TestUserCode _userCode = null;
    	TestEntities _flow = null;
    	static Reporter reporter;
    	int reportLevelInTree;
        HP.ST.Fwk.ReportCreator.QTPEngine.QTPEngineReportCreator reportCreator;
    	
    	public BindDirection bind_dir6 = null;
        public BindDirection bind_dir7 = null;
        
        public IEnumerable<FeaturesGroup> LicensedFeatures
        {
        
        get
        {
        List<FeaturesGroup> features = new List<FeaturesGroup>();
        FeaturesGroup fg1 = new FeaturesGroup();
            fg1.Add(new LicenseFeature("UnifiedFunctionalTesting","1.0"));
            fg1.Add(new LicenseFeature("UnifiedFunctionalTesting","1.1"));
            fg1.Add(new LicenseFeature("UnifiedFunctionalTesting","1.2"));
            features.Add(fg1);
            FeaturesGroup fg2 = new FeaturesGroup();
            FeaturesGroup fg3 = new FeaturesGroup();
            FeaturesGroup fg4 = new FeaturesGroup();
            FeaturesGroup fg5 = new FeaturesGroup();
            return features;
        
        }
        
        }
        
        public WorkFlowScript()
            : base(VuserClass.CommandLineArguments, new STRunTimeContext(), "test")
        {	
        	UpdateContextWithActionFolder(String.Empty);
        	
        }
        
        public WorkFlowScript(ISTRunTimeContext ctx)
            : base(VuserClass.CommandLineArguments, ctx, "test")
            
        {
        	this._context = ctx;
        	UpdateContextWithActionFolder(String.Empty);
        	UpdateTestSettings(ctx);
        }
        
        internal void InitializeComponent()
        {
        	LoadInput();
        	
        	InitReport();
        	
        	InitializeEncryptionManagerValues();
        
        	_userCode = new TestUserCode();
            _flow = _userCode;
            _flow.Context=this._context;
            
            
        
        	_flow.DataFetchActivity23 = new HP.ST.Ext.BasicActivities.DataFetchActivity(_context,"DataFetchActivity23");
            _flow.StartActivity1 = new HP.ST.Ext.BasicActivities.StartActivity(_context,"StartActivity1");
            _flow.Loop2 = new HP.ST.Fwk.RunTimeFWK.CompositeActivities.Loop<Loop2Input>(_context,"Loop2",LoopType.For);
            _flow.DataExporterActivity25 = new HP.ST.Ext.BasicActivities.DataExporterActivity(_context,"DataExporterActivity25");
            _flow.DataExporterCloseActivity26 = new HP.ST.Ext.BasicActivities.DataExporterCloseActivity(_context,"DataExporterCloseActivity26");
            _flow.EndActivity3 = new HP.ST.Ext.BasicActivities.EndActivity(_context,"EndActivity3");
            _flow.DataDisconnectActivity24 = new HP.ST.Ext.BasicActivities.DataDisconnectActivity(_context,"DataDisconnectActivity24");
            _flow.Sequence22 = new HP.ST.Fwk.RunTimeFWK.CompositeActivities.Sequence(_context,"Sequence22");
            _flow.CallQTPTest13 = new HP.ST.Ext.UFTActivity.QtpTestActivity(_context,"CallQTPTest13");
            _flow.IfElse14 = new HP.ST.Fwk.RunTimeFWK.CompositeActivities.IfElse<IfElse14Input>(_context,"IfElse14");
            _flow.IfElseBranch15 = new HP.ST.Fwk.RunTimeFWK.CompositeActivities.IfElseBranch(_context,"IfElseBranch15");
            _flow.IfElseBranch16 = new HP.ST.Fwk.RunTimeFWK.CompositeActivities.IfElseBranch(_context,"IfElseBranch16");
            _flow.CallQTPTest19 = new HP.ST.Ext.UFTActivity.QtpTestActivity(_context,"CallQTPTest19");
            _flow.CallQTPTest18 = new HP.ST.Ext.UFTActivity.QtpTestActivity(_context,"CallQTPTest18");
            _flow.CallQTPTest20 = new HP.ST.Ext.UFTActivity.QtpTestActivity(_context,"CallQTPTest20");
            _flow.CallQTPTest21 = new HP.ST.Ext.UFTActivity.QtpTestActivity(_context,"CallQTPTest21");
            _flow.ReportMessageActivity17 = new HP.ST.Ext.BasicActivities.ReportMessageActivity(_context,"ReportMessageActivity17");
            _flow.DataFetchActivity23.Comment = @"";
            _flow.DataFetchActivity23.IconPath = @"";
            _flow.DataFetchActivity23.AssemblyPath = @"AddIns\ServiceTest\BaseDataProviders\HP.ST.Ext.CustomDataProviders.dll";
            _flow.DataFetchActivity23.QueryClassName = @"HP.ST.Ext.CustomDataProviders.ExcelFileDataQuery";
            XmlDocument DataFetchActivity23_QueryParameters_Document = new XmlDocument();
            DataFetchActivity23_QueryParameters_Document.PreserveWhitespace = true;
            string xmlDataFetchActivity23Params = @"<Arguments><QueryParametersContainer><QueryParameter><Name>Id</Name><Value>21c659eb-6361-4dca-978d-d9aaa00952c5</Value></QueryParameter><QueryParameter><Name>QueryName</Name><Value>GenerateTestData!Global</Value></QueryParameter><QueryParameter><Name>IsEmbedded</Name><Value>True</Value></QueryParameter><QueryParameter><Name>Externalized</Name><Value>False</Value></QueryParameter><QueryParameter><Name>GroupText</Name><Value>GenerateTestData</Value></QueryParameter><QueryParameter><Name>FilePath</Name><Value>" + _context.ResourceManager.GetValue("{GenerateTestData!Global.TablePath}") + "</Value></QueryParameter><QueryParameter><Name>SheetName</Name><Value>Global$</Value></QueryParameter><QueryParameter><Name>ContainsHeadersRow</Name><Value>True</Value></QueryParameter></QueryParametersContainer></Arguments>";
            DataFetchActivity23_QueryParameters_Document.LoadXml(xmlDataFetchActivity23Params);
            _flow.DataFetchActivity23.QueryParameters = DataFetchActivity23_QueryParameters_Document;
            _flow.dataSourceNameToDataSource.Add("GenerateTestData!Global", _flow.DataFetchActivity23);
            this.Activities.Add (_flow.DataFetchActivity23);
            _flow.StartActivity1.Comment = @"";
            _flow.StartActivity1.IconPath = @"AddIns\ServiceTest\BasicActivities\toolbox_code_activity.png";
            _flow.StartActivity1.Name = @"Start";
            _flow.StartActivity1.JVM = new HP.ST.Ext.BasicActivities.JVMProperties();
            _flow.StartActivity1.IsJavaUsed = false;
            _flow.StartActivity1.JVM.Classpath = @"%CLASSPATH%";
            _flow.StartActivity1.JVM.AdditionalVMParameters = @"";
            _flow.StartActivity1.JMS = new HP.ST.Ext.BasicActivities.JMSProperties();
            _flow.StartActivity1.IsJmsUsed = false;
            _flow.StartActivity1.JMS.JNDIContextFactory = @"<Select...>";
            _flow.StartActivity1.JMS.JNDIProviderUrl = @"";
            _flow.StartActivity1.JMS.JMSConnectionFactory = @"";
            _flow.StartActivity1.JMS.SecurityPrincipal = @"";
            _flow.StartActivity1.JMS.SecurityCredentials = @"";
            _flow.StartActivity1.JMS.JMSClientID = @"";
            _flow.StartActivity1.JMS.SSLPassword = @"";
            _flow.StartActivity1.JMS.SSLTrustedCertificate = @"";
            _flow.StartActivity1.JMS.SSLIdentity = @"";
            _flow.StartActivity1.JMS.ConnectionsPerProcess = @"1";
            _flow.StartActivity1.JMS.TimeoutOptions = @"DN_User_defined_Timeout";
            _flow.StartActivity1.JMS.UserTimeout = @"20";
            _flow.StartActivity1.JMS.GenerateAutoSelector = @"No";
            this.Activities.Add (_flow.StartActivity1);
            _flow.Loop2.ConditionAsString = @"Run for 1 iteration";
            _flow.Loop2.NumberOfIterations = (int)1;
            _flow.Loop2.Comment = @"";
            _flow.Loop2.IconPath = @"AddIns\ServiceTest\BasicActivities\toolbox_loop.png";
            _flow.Loop2.Name = @"Test Flow";
            _flow.Loop2.Activities.Add (_flow.Sequence22);
            this.Activities.Add (_flow.Loop2);
            _flow.DataExporterActivity25.Comment = @"";
            _flow.DataExporterActivity25.IconPath = @"";
            VTDPropertyInfoBase pi14 = new VTDPropertyInfoBase("OutTable");
            VTDBaseGetter binding_getter9 = new VTDObjectGetter(pi14);
            VTDPropertyInfoBase pi15 = new VTDPropertyInfoBase("Data");
            VTDBaseSetter binding_setter6 = new VTDObjectSetter(pi15);
            binding_setter6 = new StringFormaterDecorator(binding_setter6,"{Step.DataFetchActivity23.OutTable}");
            bind_dir6 = new BindDirection(_flow.DataFetchActivity23,binding_getter9,binding_setter6,BindTargetType.ToInProperty);
            _flow.DataExporterActivity25.InDirections.Add(bind_dir6);
            this.Activities.Add (_flow.DataExporterActivity25);
            _flow.DataExporterCloseActivity26.Comment = @"";
            _flow.DataExporterCloseActivity26.IconPath = @"";
            this.Activities.Add (_flow.DataExporterCloseActivity26);
            _flow.EndActivity3.Comment = @"";
            _flow.EndActivity3.IconPath = @"AddIns\ServiceTest\BasicActivities\toolbox_code_activity.png";
            _flow.EndActivity3.Name = @"End";
            this.Activities.Add (_flow.EndActivity3);
            _flow.DataDisconnectActivity24.Comment = @"";
            _flow.DataDisconnectActivity24.IconPath = @"";
            VTDPropertyInfoBase pi16 = new VTDPropertyInfoBase("OutTable");
            VTDBaseGetter binding_getter10 = new VTDObjectGetter(pi16);
            VTDPropertyInfoBase pi17 = new VTDPropertyInfoBase("Data");
            VTDBaseSetter binding_setter7 = new VTDObjectSetter(pi17);
            binding_setter7 = new StringFormaterDecorator(binding_setter7,"{Step.DataFetchActivity23.OutTable}");
            bind_dir7 = new BindDirection(_flow.DataFetchActivity23,binding_getter10,binding_setter7,BindTargetType.ToInProperty);
            _flow.DataDisconnectActivity24.InDirections.Add(bind_dir7);
            this.Activities.Add (_flow.DataDisconnectActivity24);
            _flow.Sequence22.Comment = @"";
            _flow.Sequence22.IconPath = @"";
            _flow.Sequence22.Name = @"Sequence22";
            _flow.Sequence22.Activities.Add (_flow.CallQTPTest13);
            _flow.Sequence22.Activities.Add (_flow.IfElse14);
            XmlDocument CallQTPTest13_InputArguments_Document = new XmlDocument();
            CallQTPTest13_InputArguments_Document.PreserveWhitespace = true;
            CallQTPTest13_InputArguments_Document.LoadXml(
@"<Arguments><Agent></Agent><Password></Password></Arguments>");
            _flow.CallQTPTest13.InputArguments = CallQTPTest13_InputArguments_Document;
            _flow.CallQTPTest13.Comment = @"";
            _flow.CallQTPTest13.IconPath = @"AddIns\ServiceTest\UFT\toolbox_qtp.png";
            _flow.CallQTPTest13.Name = @"Create New Order.FR - Login";
            _flow.CallQTPTest13.ScriptPath = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest13.ScriptPath}")) ? @"..\Create New Order" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest13.ScriptPath}");
            _flow.CallQTPTest13.ActionName = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest13.ActionName}")) ? @"FR - Login" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest13.ActionName}");
            _flow.CallQTPTest13.Description = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest13.Description}")) ? @"" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest13.Description}");
            _flow.CallQTPTest13.IsActionSelected = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest13.IsActionSelected}")) ? @"True" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest13.IsActionSelected}");
            _flow.CallQTPTest13.ResultLocation = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest13.ResultLocation}")) ? @"RunQTPReport\" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest13.ResultLocation}");
            _flow.CallQTPTest13.QCScriptPath = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest13.QCScriptPath}")) ? @"" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest13.QCScriptPath}");
            _flow.IfElse14.ConditionAsString = @"{Step.OutputProperties.CallQTPTest13.Logged_In} Equal True";
            _flow.IfElse14.Comment = @"";
            _flow.IfElse14.IconPath = @"AddIns\ServiceTest\BasicActivities\toolbox_if_else.png";
            _flow.IfElse14.Name = @"Login Successful";
            _flow.IfElse14.Activities.Add (_flow.IfElseBranch15);
            _flow.IfElse14.Activities.Add (_flow.IfElseBranch16);
            _flow.IfElseBranch15.Condition += delegate(object sender,EventArgs e)
            {
            	try
            	{
            VTDPropertyInfoBase pi18 = new VTDPropertyInfoBase("OutputArguments","/*[local-name(.)='Arguments'][1]/*[local-name(.)='Logged_In'][1]");
            VTDBaseGetter binding_getter11 = new VTDXPathGetter(pi18,XmlTypeCode.Boolean);
            		System.Boolean expr00 = (System.Boolean)HP.ST.Fwk.RunTimeFWK.Utilities.Utils.ConvertValue(_flow.CallQTPTest13.GetParam(binding_getter11),typeof(System.Boolean));
            		var result0 = expr00;
            		System.Boolean result1 = (System.Boolean)(true);
            		return (result0 == result1);
            	}
            	catch(Exception exp)
            	{
            		if (exp is System.InvalidCastException)
            		{
            			throw;
            		}
            		else
            		{
            			return false;
            		}
            	};
            };
            _flow.IfElseBranch15.Comment = @"";
            _flow.IfElseBranch15.IconPath = @"";
            _flow.IfElseBranch15.Name = @"Yes";
            _flow.IfElseBranch15.Activities.Add (_flow.CallQTPTest19);
            _flow.IfElseBranch15.Activities.Add (_flow.CallQTPTest18);
            _flow.IfElseBranch15.Activities.Add (_flow.CallQTPTest20);
            _flow.IfElseBranch15.Activities.Add (_flow.CallQTPTest21);
            _flow.IfElseBranch16.Condition += delegate(object sender,EventArgs e)
            {
            return true;
            };
            _flow.IfElseBranch16.Comment = @"";
            _flow.IfElseBranch16.IconPath = @"";
            _flow.IfElseBranch16.Name = @"No";
            _flow.IfElseBranch16.Activities.Add (_flow.ReportMessageActivity17);
            XmlDocument CallQTPTest19_InputArguments_Document = new XmlDocument();
            CallQTPTest19_InputArguments_Document.PreserveWhitespace = true;
            CallQTPTest19_InputArguments_Document.LoadXml(
@"<Arguments><FlyFrom>Denver</FlyFrom><FlyTo>Paris</FlyTo><Date>27/01/2021</Date><Class>Business</Class><NumOfTickets>2</NumOfTickets></Arguments>");
            _flow.CallQTPTest19.InputArguments = CallQTPTest19_InputArguments_Document;
            _flow.CallQTPTest19.Comment = @"";
            _flow.CallQTPTest19.IconPath = @"AddIns\ServiceTest\UFT\toolbox_qtp.png";
            _flow.CallQTPTest19.Name = @"Create New Order.FR - Find a Flight";
            _flow.CallQTPTest19.ScriptPath = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest19.ScriptPath}")) ? @"..\Create New Order" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest19.ScriptPath}");
            _flow.CallQTPTest19.ActionName = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest19.ActionName}")) ? @"FR - Find a Flight" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest19.ActionName}");
            _flow.CallQTPTest19.Description = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest19.Description}")) ? @"" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest19.Description}");
            _flow.CallQTPTest19.IsActionSelected = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest19.IsActionSelected}")) ? @"True" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest19.IsActionSelected}");
            _flow.CallQTPTest19.ResultLocation = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest19.ResultLocation}")) ? @"RunQTPReport\" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest19.ResultLocation}");
            _flow.CallQTPTest19.QCScriptPath = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest19.QCScriptPath}")) ? @"" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest19.QCScriptPath}");
            _flow.CallQTPTest18.Comment = @"";
            _flow.CallQTPTest18.IconPath = @"AddIns\ServiceTest\UFT\toolbox_qtp.png";
            _flow.CallQTPTest18.Name = @"Create New Order.FR - Select Flight";
            _flow.CallQTPTest18.ScriptPath = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest18.ScriptPath}")) ? @"..\Create New Order" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest18.ScriptPath}");
            _flow.CallQTPTest18.ActionName = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest18.ActionName}")) ? @"FR - Select Flight" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest18.ActionName}");
            _flow.CallQTPTest18.Description = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest18.Description}")) ? @"" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest18.Description}");
            _flow.CallQTPTest18.IsActionSelected = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest18.IsActionSelected}")) ? @"True" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest18.IsActionSelected}");
            _flow.CallQTPTest18.ResultLocation = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest18.ResultLocation}")) ? @"RunQTPReport\" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest18.ResultLocation}");
            _flow.CallQTPTest18.QCScriptPath = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest18.QCScriptPath}")) ? @"" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest18.QCScriptPath}");
            XmlDocument CallQTPTest20_InputArguments_Document = new XmlDocument();
            CallQTPTest20_InputArguments_Document.PreserveWhitespace = true;
            CallQTPTest20_InputArguments_Document.LoadXml(
@"<Arguments><Passenger>Amir Khan</Passenger></Arguments>");
            _flow.CallQTPTest20.InputArguments = CallQTPTest20_InputArguments_Document;
            _flow.CallQTPTest20.Comment = @"";
            _flow.CallQTPTest20.IconPath = @"AddIns\ServiceTest\UFT\toolbox_qtp.png";
            _flow.CallQTPTest20.Name = @"Create New Order.FR - Enter Passenger Details";
            _flow.CallQTPTest20.ScriptPath = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest20.ScriptPath}")) ? @"..\Create New Order" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest20.ScriptPath}");
            _flow.CallQTPTest20.ActionName = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest20.ActionName}")) ? @"FR - Enter Passenger Details" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest20.ActionName}");
            _flow.CallQTPTest20.Description = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest20.Description}")) ? @"" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest20.Description}");
            _flow.CallQTPTest20.IsActionSelected = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest20.IsActionSelected}")) ? @"True" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest20.IsActionSelected}");
            _flow.CallQTPTest20.ResultLocation = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest20.ResultLocation}")) ? @"RunQTPReport\" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest20.ResultLocation}");
            _flow.CallQTPTest20.QCScriptPath = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest20.QCScriptPath}")) ? @"" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest20.QCScriptPath}");
            _flow.CallQTPTest21.Comment = @"";
            _flow.CallQTPTest21.IconPath = @"AddIns\ServiceTest\UFT\toolbox_qtp.png";
            _flow.CallQTPTest21.Name = @"Create New Order.FR - Close App";
            _flow.CallQTPTest21.ScriptPath = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest21.ScriptPath}")) ? @"..\Create New Order" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest21.ScriptPath}");
            _flow.CallQTPTest21.ActionName = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest21.ActionName}")) ? @"FR - Close App" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest21.ActionName}");
            _flow.CallQTPTest21.Description = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest21.Description}")) ? @"" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest21.Description}");
            _flow.CallQTPTest21.IsActionSelected = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest21.IsActionSelected}")) ? @"True" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest21.IsActionSelected}");
            _flow.CallQTPTest21.ResultLocation = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest21.ResultLocation}")) ? @"RunQTPReport\" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest21.ResultLocation}");
            _flow.CallQTPTest21.QCScriptPath = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest21.QCScriptPath}")) ? @"" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest21.QCScriptPath}");
            _flow.ReportMessageActivity17.Status = @"Done";
            _flow.ReportMessageActivity17.Message = @"Login Failed";
            _flow.ReportMessageActivity17.Destination = @"ReportAndOutput";
            _flow.ReportMessageActivity17.Comment = @"";
            _flow.ReportMessageActivity17.IconPath = @"AddIns\ServiceTest\BasicActivities\toolbox_report_message.png";
            _flow.ReportMessageActivity17.Name = @"Message Login Failed";
            
        }
        
        internal void InitializeEncryptionManagerValues()
        {
        
        }
        	
    	bool useReport = true;
    
    	protected override STExecutionResult ExecuteStep()
        {
            return base.ExecuteStep();
        }
    
        public void Start()
        {
    	    try
    		{
    		  Workflow_Executing();
    		  this.ExecuteStep();
    		}
    		finally
    		{
    		  WorkFlowScript_Completed();
    		}
        }
    
    	private void InitReport()
    	{
    		if (useReport)
    		{	
    			// Intialize Reporter
    			string reportDBDir = Path.Combine(this._context.ReportDirectory, @"Report");
    			CleanupReport(reportDBDir);        	
    			string reportDBPath = Path.Combine(reportDBDir, "VTDReport.mdb");        	
    			if (reporter == null)
    			{
    				reporter = new Reporter(reportDBPath);
    			}
    			_context.Reporter = reporter;
    		}
    	}
    
        public static void CopyDirectory(string Src, string Dst)
        {
            String[] Files;
    
            if (Dst[Dst.Length - 1] != Path.DirectorySeparatorChar)
                Dst += Path.DirectorySeparatorChar;
            if (!Directory.Exists(Dst)) Directory.CreateDirectory(Dst);
            Files = Directory.GetFileSystemEntries(Src);
            foreach (string Element in Files)
            {
                // Sub directories
                if (Directory.Exists(Element))
                    CopyDirectory(Element, Dst + Path.GetFileName(Element));
                // Files in directory
                else
                    File.Copy(Element, Dst + Path.GetFileName(Element), true);
            }
        }
        
        private void CleanupReport(string reportDBDir)
        {   
    		if (useReport)
    		{             
    			string reportTemplateDir = Path.Combine(ServiceTestRunner.GetInstallPath(),@"bin\ReportResources");                
    			try
    			{
            		CopyDirectory(reportTemplateDir, reportDBDir);
    			}
    			catch //(Exception ex)
    			{
    				//ToDo: LoggingService.Warn("Report Cleanup Error", ex);
    			}
    		}
        }
    
        void Workflow_Executing()
        {   
        	InitReportNode();
                       
        }
    
    	private void InitReportNode()
    	{
    		if (useReport)
    		{	
        		// Init report creator
    			this.reportCreator = new HP.ST.Fwk.ReportCreator.QTPEngine.QTPEngineReportCreator();
    			this.reportLevelInTree = reportCreator.Init(_context.EnvironmentProfile.GetVariableValue("TestName"), _context);
                
    			STActivityBase activity = this;
    			string workflowID = activity.GetHashCode().ToString();
    			ReportNodeCreationData newNodeData =
    			new ReportNodeCreationData(workflowID, workflowID, DateTime.Now);
    			reporter.CreateReportNode(newNodeData);
            
    			ReportInfoData newReportData = new ReportInfoData(workflowID, ReportKeywords.TypeKeywordTag, this.GetType().ToString());
    			reporter.SendReportData(newReportData);
    			newReportData = new ReportInfoData(workflowID, ReportKeywords.NameKeywordTag, this.Name);
    			//TrackData(ReportInfoData.InfoDataTag, newReportData);
    			reporter.SendReportData(newReportData);            
            }
    	}
        
        void WorkFlowScript_Completed()
        {   
    		
    
    		CreateReportFiles();
    					
        	// Write all snapshots to disk
    		this._context.SnapshotManager.WriteSnapshotsToDisk();
    
    		OnExecutionCompleted();
    		
        }
    
    	private void CreateReportFiles()
    	{
    		if (useReport)
    		{	
    			//Dispose reporter inorder to close connection to report DB
           		this._context.Reporter.Dispose();
            	
           		// Run report creator
    			reportCreator.RunOnDBAndCreateFiles();
    		}
    	}
    
        
        void Workflow_Faulting()
        {
    		
    
    		CreateReportFiles();
            // Write all snapshots to disk
    		this._context.SnapshotManager.WriteSnapshotsToDisk();
           
    		OnExecutionCompleted();
        }
    
    	protected override QcSystemVariables GetRuntimeQcVariables(ISTRunTimeContext context)
    	{
    		return new HP.ST.Ext.BasicActivities.RuntimeQcVariables(this._context);
    	}
            
    	protected override TestSystemVariables GetTestSystemVariables(ISTRunTimeContext context)
    	{
    		return new HP.ST.Ext.BasicActivities.RuntimeTestVariables(this._context);
    	}
    
    	private void UpdateTestSettings(ISTRunTimeContext ctx)
        {
    		ctx.PropertyBag["StopTestOnStepFailure"] = true;
    	}
    }
    
    public partial class VuserClass
    {
    	public static string[] CommandLineArguments;
    	public static string[] DotNetResolverPaths;
    	
        public VuserClass()
        {
    				
    		AssemblyResolver.AddSTPathsToResolutionPaths();
    		AssemblyResolver.AttachToAppdomain();
        }
    
        private void AddAssemblyResolver()
        {
    		AssemblyResolver.AddTestPathToResolutionPaths(GetTestPath());
    		AssemblyResolver.AddPathsForAssemblyResolution(DotNetResolverPaths);
        }
    	
        public int STAction()
        {	
            AddAssemblyResolver();
            STRunTimeContext ctx = new STRunTimeContext(Directory.GetParent(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)).FullName, string.Empty);
            WorkFlowScript script = new WorkFlowScript(ctx);
            script.InitializeComponent();
            script.Start();       
            
            return 0;
        }
        
        public void NotifyLicenseException(string msg)
        {
        		
    		try
    		{
    		    STRunTimeContext ctx = new STRunTimeContext(Directory.GetParent(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)).FullName, string.Empty);
                WorkFlowScript script = new WorkFlowScript(ctx);
                script.InitializeComponent();
                script.Context.ReplayClient.OnLicenseFailure(msg);
                
            }
            catch (Exception)
            {
    			// ToDo: log the error message
            }        
        }
    
    	 protected string GetTestPath()
            {
                if (CommandLineArguments != null)
                {
                    for (int i = 0; i < CommandLineArguments.Length; i++)
                    {
                        if (CommandLineArguments[i].Equals("-test", StringComparison.OrdinalIgnoreCase))
                        {
                            return CommandLineArguments[i + 1];
                        }
                    }
                }
                return String.Empty;
            }
        
    }
    
    }
    